# $FreeBSD: releng/11.1/usr.bin/clang/llvm-dwarfdump/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-dwarfdump

SRCDIR=		tools/llvm-dwarfdump
SRCS+=		llvm-dwarfdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
