# $FreeBSD: releng/11.1/usr.bin/clang/llvm-pdbdump/Makefile 316423 2017-04-02 17:24:58Z dim $

PROG_CXX=	llvm-pdbdump
MAN=

SRCDIR=		tools/llvm-pdbdump
SRCS+=		PrettyBuiltinDumper.cpp
SRCS+=		PrettyClassDefinitionDumper.cpp
SRCS+=		PrettyCompilandDumper.cpp
SRCS+=		PrettyEnumDumper.cpp
SRCS+=		PrettyExternalSymbolDumper.cpp
SRCS+=		PrettyFunctionDumper.cpp
SRCS+=		PrettyTypeDumper.cpp
SRCS+=		PrettyTypedefDumper.cpp
SRCS+=		PrettyVariableDumper.cpp
SRCS+=		LLVMOutputStyle.cpp
SRCS+=		LinePrinter.cpp
SRCS+=		PdbYaml.cpp
SRCS+=		YAMLOutputStyle.cpp
SRCS+=		YamlSymbolDumper.cpp
SRCS+=		YamlTypeDumper.cpp
SRCS+=		llvm-pdbdump.cpp

.include "../llvm.prog.mk"
