# $FreeBSD: releng/11.1/lib/libnetbsd/Makefile 316098 2017-03-28 13:39:04Z vangyzen $

.include <bsd.own.mk>

PACKAGE=lib${LIB}
LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	sockaddr_snprintf.c strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
