# $FreeBSD: releng/11.1/lib/libclang_rt/include/Makefile 310618 2016-12-26 20:36:37Z dim $

.include <bsd.init.mk>

.PATH:		${CRTSRC}/include/sanitizer

INCSDIR=	${CLANGDIR}/include/sanitizer

INCS+=		allocator_interface.h
INCS+=		asan_interface.h
INCS+=		common_interface_defs.h
INCS+=		coverage_interface.h
INCS+=		dfsan_interface.h
INCS+=		esan_interface.h
INCS+=		linux_syscall_hooks.h
INCS+=		lsan_interface.h
INCS+=		msan_interface.h
INCS+=		tsan_interface_atomic.h

.include <bsd.prog.mk>
