#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: releng/11.1/usr.bin/rsh/Makefile 319186 2017-05-30 04:27:05Z ngie $

PROG=	rsh
CFLAGS+=-I${SRCTOP}/libexec/rlogind

PACKAGE=rcmds

BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
