# $FreeBSD: releng/11.1/usr.bin/clang/llvm-bcanalyzer/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-bcanalyzer

SRCDIR=		tools/llvm-bcanalyzer
SRCS+=		llvm-bcanalyzer.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
