# $FreeBSD: releng/11.1/usr.bin/clang/llvm-diff/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-diff

SRCDIR=		tools/llvm-diff
SRCS+=		DiffConsumer.cpp
SRCS+=		DiffLog.cpp
SRCS+=		DifferenceEngine.cpp
SRCS+=		llvm-diff.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
