# $FreeBSD: releng/11.1/usr.sbin/bsdinstall/scripts/Makefile 303447 2016-07-28 15:54:17Z robak $

SCRIPTS= auto adduser checksum config docsinstall entropy hardening hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= ${LIBEXECDIR}/bsdinstall

MAN=

.include <bsd.prog.mk>
