# $FreeBSD: releng/11.1/sys/modules/ntb/ntb_hw/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:  ${SRCTOP}/sys/dev/ntb/ntb_hw

KMOD    = ntb_hw
SRCS    = ntb_hw.c
SRCS += device_if.h bus_if.h pci_if.h ntb_if.h

.include <bsd.kmod.mk>
