# $FreeBSD: releng/11.1/sys/modules/i2c/isl/Makefile 319182 2017-05-30 04:11:12Z ngie $

.PATH:		${SRCTOP}/sys/dev/isl
KMOD		= isl
SRCS		= isl.c device_if.h bus_if.h iicbus_if.h

.include <bsd.kmod.mk>
