# $FreeBSD: releng/11.1/usr.sbin/ntp/doc/drivers/scripts/Makefile 319191 2017-05-30 05:15:09Z ngie $

.include <src.opts.mk>

FILESDIR=	${SHAREDIR}/doc/ntp/drivers/scripts

.if ${MK_HTML} != "no"
FILES=	footer.txt style.css
.endif

.PATH: ${SRCTOP}/contrib/ntp/html/drivers/scripts

.include <bsd.prog.mk>
