# $FreeBSD: releng/11.1/usr.bin/lessecho/Makefile 319186 2017-05-30 04:27:05Z ngie $

PROG=	lessecho
SRCS=	lessecho.c version.c
CLEANFILES= lessecho.1

.include "${SRCTOP}/usr.bin/less/Makefile.common"
.include <bsd.prog.mk>
