#	@(#)Makefile	8.1 (Berkeley) 6/9/93
# $FreeBSD: releng/11.1/usr.sbin/pmcstudy/Makefile 280697 2015-03-26 15:40:47Z rrs $

PROG=	pmcstudy
MAN=	pmcstudy.8
SRCS= pmcstudy.c eval_expr.c
CFLAGS+= -Wall -Werror

BINDIR= /usr/bin

.include <bsd.prog.mk>

