# $FreeBSD: releng/11.1/usr.sbin/chown/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

.include <bsd.own.mk>

TESTSDIR=	${TESTSBASE}/bin/chown

TAP_TESTS_SH=			chown-f_test

.include <bsd.test.mk>
