# $FreeBSD: releng/11.1/usr.sbin/cpucontrol/Makefile 308760 2016-11-17 15:16:52Z avg $

PROG=	cpucontrol
MAN=	cpucontrol.8
SRCS=	cpucontrol.c intel.c amd.c amd10h.c via.c

NO_WCAST_ALIGN=

.include <bsd.prog.mk>
