# $FreeBSD: releng/11.1/usr.bin/clang/llvm-modextract/Makefile 311310 2017-01-04 21:47:39Z dim $

PROG_CXX=	llvm-modextract
MAN=

SRCDIR=		tools/llvm-modextract
SRCS=		llvm-modextract.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
