# $FreeBSD: releng/11.1/usr.bin/clang/llvm-cxxdump/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-cxxdump
MAN=

SRCDIR=		tools/llvm-cxxdump
SRCS+=		Error.cpp
SRCS+=		llvm-cxxdump.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
