# $FreeBSD: releng/11.1/usr.bin/mkcsmapper/Makefile 319186 2017-05-30 04:27:05Z ngie $

.PATH: ${SRCTOP}/lib/libc/iconv

PROG=	mkcsmapper
LDFLAGS+= -L${SRCTOP}/lib/libc

NO_WMISSING_VARIABLE_DECLARATIONS=

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
