# $FreeBSD: releng/11.1/usr.bin/clang/llvm-link/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	llvm-link

SRCDIR=		tools/llvm-link
SRCS+=		llvm-link.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
