# $FreeBSD: releng/11.1/sbin/devd/tests/Makefile 299094 2016-05-04 23:20:53Z ngie $

ATF_TESTS_C=	client_test
TEST_METADATA.client_test=	required_programs="devd"
TEST_METADATA.client_test+=	required_user="root"
TEST_METADATA.client_test+=	timeout=15

WARNS?=	5

.include <bsd.test.mk>
