# $FreeBSD: releng/11.1/sys/modules/dtb/am335x/Makefile 312756 2017-01-25 14:49:42Z loos $
# All the dts files for am335x systems we support.
DTS=	\
	beaglebone.dts \
	beaglebone-black.dts \
	ufw.dts

.include <bsd.dtb.mk>
