# $FreeBSD: releng/11.1/usr.bin/clang/llvm-cxxfilt/Makefile 311310 2017-01-04 21:47:39Z dim $

PROG_CXX=	llvm-cxxfilt
MAN=

SRCDIR=		tools/llvm-cxxfilt
SRCS+=		llvm-cxxfilt.cpp

LIBADD+=	z

.include "../llvm.prog.mk"
