# $FreeBSD: releng/11.1/sys/modules/dtb/imx6/Makefile 314517 2017-03-01 21:31:44Z ian $
# All the dts files for imx6 systems we support.
DTS=	\
	imx6dl-cubox-i.dts \
	imx6q-cubox-i.dts \
	imx6dl-hummingboard.dts \
	imx6q-hummingboard.dts \
	imx6dl-nitrogen6x.dts \
	imx6q-nitrogen6_max.dts \
	imx6q-nitrogen6x.dts \
	imx6dl-riotboard.dts \
	imx6dl-wandboard.dts \
	imx6q-wandboard.dts

.include <bsd.dtb.mk>
