# $FreeBSD: releng/11.1/usr.bin/clang/clang-tblgen/Makefile 310618 2016-12-26 20:36:37Z dim $

PROG_CXX=	clang-tblgen
MAN=

SRCDIR=		tools/clang/utils/TableGen
SRCS+=		ClangASTNodesEmitter.cpp
SRCS+=		ClangAttrEmitter.cpp
SRCS+=		ClangCommentCommandInfoEmitter.cpp
SRCS+=		ClangCommentHTMLNamedCharacterReferenceEmitter.cpp
SRCS+=		ClangCommentHTMLTagsEmitter.cpp
SRCS+=		ClangDiagnosticsEmitter.cpp
SRCS+=		ClangSACheckersEmitter.cpp
SRCS+=		NeonEmitter.cpp
SRCS+=		TableGen.cpp

.include "../llvm.prog.mk"
