#	@(#)Makefile	8.1 (Berkeley) 5/31/93
#
# $FreeBSD: releng/11.1/usr.bin/fortune/Makefile 315349 2017-03-16 01:53:21Z ngie $

SUBDIR=	fortune strfile datfiles unstr

SUBDIR_DEPEND_datfiles=	strfile

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
