# $FreeBSD: releng/11.1/sys/modules/i2c/Makefile 308370 2016-11-06 13:53:50Z avg $

SUBDIR =
SUBDIR += controllers if_ic smbus iicbus iicbb iicsmb iic cyapa smb isl jedec_ts

.include <bsd.subdir.mk>
